// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MOWCommon.proto

#ifndef PROTOBUF_MOWCommon_2eproto__INCLUDED
#define PROTOBUF_MOWCommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace PbMOWCommon {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MOWCommon_2eproto();
void protobuf_AssignDesc_MOWCommon_2eproto();
void protobuf_ShutdownFile_MOWCommon_2eproto();

class PbMOWVector3;
class PbMOWVector4;

// ===================================================================

class PbMOWVector3 : public ::google::protobuf::Message {
 public:
  PbMOWVector3();
  virtual ~PbMOWVector3();

  PbMOWVector3(const PbMOWVector3& from);

  inline PbMOWVector3& operator=(const PbMOWVector3& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PbMOWVector3& default_instance();

  void Swap(PbMOWVector3* other);

  // implements Message ----------------------------------------------

  PbMOWVector3* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PbMOWVector3& from);
  void MergeFrom(const PbMOWVector3& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);

  // optional float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);

  // optional float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);

  // @@protoc_insertion_point(class_scope:PbMOWCommon.PbMOWVector3)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float x_;
  float y_;
  float z_;
  friend void  protobuf_AddDesc_MOWCommon_2eproto();
  friend void protobuf_AssignDesc_MOWCommon_2eproto();
  friend void protobuf_ShutdownFile_MOWCommon_2eproto();

  void InitAsDefaultInstance();
  static PbMOWVector3* default_instance_;
};
// -------------------------------------------------------------------

class PbMOWVector4 : public ::google::protobuf::Message {
 public:
  PbMOWVector4();
  virtual ~PbMOWVector4();

  PbMOWVector4(const PbMOWVector4& from);

  inline PbMOWVector4& operator=(const PbMOWVector4& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PbMOWVector4& default_instance();

  void Swap(PbMOWVector4* other);

  // implements Message ----------------------------------------------

  PbMOWVector4* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PbMOWVector4& from);
  void MergeFrom(const PbMOWVector4& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline double x() const;
  inline void set_x(double value);

  // optional double y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline double y() const;
  inline void set_y(double value);

  // optional double z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline double z() const;
  inline void set_z(double value);

  // optional double w = 4;
  inline bool has_w() const;
  inline void clear_w();
  static const int kWFieldNumber = 4;
  inline double w() const;
  inline void set_w(double value);

  // @@protoc_insertion_point(class_scope:PbMOWCommon.PbMOWVector4)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_w();
  inline void clear_has_w();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  double w_;
  friend void  protobuf_AddDesc_MOWCommon_2eproto();
  friend void protobuf_AssignDesc_MOWCommon_2eproto();
  friend void protobuf_ShutdownFile_MOWCommon_2eproto();

  void InitAsDefaultInstance();
  static PbMOWVector4* default_instance_;
};
// ===================================================================


// ===================================================================

// PbMOWVector3

// optional float x = 1;
inline bool PbMOWVector3::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PbMOWVector3::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PbMOWVector3::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PbMOWVector3::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float PbMOWVector3::x() const {
  // @@protoc_insertion_point(field_get:PbMOWCommon.PbMOWVector3.x)
  return x_;
}
inline void PbMOWVector3::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:PbMOWCommon.PbMOWVector3.x)
}

// optional float y = 2;
inline bool PbMOWVector3::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PbMOWVector3::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PbMOWVector3::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PbMOWVector3::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float PbMOWVector3::y() const {
  // @@protoc_insertion_point(field_get:PbMOWCommon.PbMOWVector3.y)
  return y_;
}
inline void PbMOWVector3::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:PbMOWCommon.PbMOWVector3.y)
}

// optional float z = 3;
inline bool PbMOWVector3::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PbMOWVector3::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PbMOWVector3::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PbMOWVector3::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float PbMOWVector3::z() const {
  // @@protoc_insertion_point(field_get:PbMOWCommon.PbMOWVector3.z)
  return z_;
}
inline void PbMOWVector3::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:PbMOWCommon.PbMOWVector3.z)
}

// -------------------------------------------------------------------

// PbMOWVector4

// optional double x = 1;
inline bool PbMOWVector4::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PbMOWVector4::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PbMOWVector4::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PbMOWVector4::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double PbMOWVector4::x() const {
  // @@protoc_insertion_point(field_get:PbMOWCommon.PbMOWVector4.x)
  return x_;
}
inline void PbMOWVector4::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:PbMOWCommon.PbMOWVector4.x)
}

// optional double y = 2;
inline bool PbMOWVector4::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PbMOWVector4::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PbMOWVector4::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PbMOWVector4::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double PbMOWVector4::y() const {
  // @@protoc_insertion_point(field_get:PbMOWCommon.PbMOWVector4.y)
  return y_;
}
inline void PbMOWVector4::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:PbMOWCommon.PbMOWVector4.y)
}

// optional double z = 3;
inline bool PbMOWVector4::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PbMOWVector4::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PbMOWVector4::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PbMOWVector4::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double PbMOWVector4::z() const {
  // @@protoc_insertion_point(field_get:PbMOWCommon.PbMOWVector4.z)
  return z_;
}
inline void PbMOWVector4::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:PbMOWCommon.PbMOWVector4.z)
}

// optional double w = 4;
inline bool PbMOWVector4::has_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PbMOWVector4::set_has_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PbMOWVector4::clear_has_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PbMOWVector4::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline double PbMOWVector4::w() const {
  // @@protoc_insertion_point(field_get:PbMOWCommon.PbMOWVector4.w)
  return w_;
}
inline void PbMOWVector4::set_w(double value) {
  set_has_w();
  w_ = value;
  // @@protoc_insertion_point(field_set:PbMOWCommon.PbMOWVector4.w)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PbMOWCommon

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MOWCommon_2eproto__INCLUDED
